language: csharp
solution: NFixture-Factory.sln
mono:
  - latest
install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console
script:
  - xbuildNFixture-Factory.sln
  - nunit-console ./NFixtureFactoryTest/bin/Release/NFixtureFactory.Test.dll
