language: csharp
solution: NFixture-Factory.sln
mono:
  - latest
env:
  - SECRET_TOKEN=token
after_success: 
 - nuget pack ./src/NFixtureFactory/NFixtureFactory.nuspec
 - nuget setApiKey SECRET_TOKEN
 - nuget push *.nupkg
install:
  - sudo apt-get install -y gtk-sharp2
  - nuget restore ./src/NFixture-Factory.sln  
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release ./src/NFixture-Factory.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./src/NFixtureFactoryTest/bin/Release/NFixtureFactory.Tests.dll
 
