language: csharp
solution: NFixture-Factory.sln
mono:
  - latest
install:
 - sudo apt-get install nunit-console
 - nuget restore NFixture-Factory.sln
script:
  - xbuild /p:Configuration=Release NFixture-Factory.sln
  - nunit-console ./NFixtureFactoryTest/bin/Release/NFixtureFactory.Test.dll
