language: csharp
solution: NFixture-Factory.sln
mono:
  - latest
install:
  - nuget restore NFixture-Factory.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release NFixture-Factory.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./NFixtureFactory/NFixtureFactoryTest/bin/Release/NFixtureFactory.Test.dll
