language: csharp
solution: NFixture-Factory.sln
mono:
  - latest
after_success:
 - nuget spec ./NFixtureFactoryTest/bin/Release/NFixtureFactory.dll
 - nuget setApiKey '4def1252-4498-462e-b5fc-5e68988c8812'
 - nuget push ./NFixtureFactoryTest/bin/Release/NFixtureFactory.dll.nuspec
install:
  - sudo apt-get install -y gtk-sharp2
  - nuget restore NFixture-Factory.sln  
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
  - nuget install OpenCover -Version 4.6.166 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release NFixture-Factory.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./NFixtureFactoryTest/bin/Release/NFixtureFactory.Tests.dll
 
