language: csharp
solution: NFixture-Factory.sln
mono:
  - latest
install:
  - sudo apt-get install -y gtk-sharp2
  - nuget restore NFixture-Factory.sln  
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release NFixture-Factory.sln
 
